"""add_email_attempts_table

Revision ID: 03600407b8f4
Revises: 08f63d93fb23
Create Date: 2026-01-05 15:21:01.077917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03600407b8f4'
down_revision = '08f63d93fb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('confirmation_code', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_attempts_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_attempts_email'))

    op.drop_table('email_attempts')
    # ### end Alembic commands ###
