"""Add confirmation_sent_at, created_at, updated_at fields to User

Revision ID: 08f63d93fb23
Revises: a7fef1a5eb6a
Create Date: 2026-01-03 16:10:25.326156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f63d93fb23'
down_revision = 'a7fef1a5eb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmation_sent_at')

    # ### end Alembic commands ###
