"""Change estimated_cost to Float

Revision ID: 46f86e2b027c
Revises: a0b4866beb85
Create Date: 2025-09-19 21:27:50.692050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f86e2b027c'
down_revision = 'a0b4866beb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('car_brand', sa.String(length=50), nullable=True),
    sa.Column('car_model', sa.String(length=50), nullable=True),
    sa.Column('desired_date', sa.Date(), nullable=True),
    sa.Column('desired_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('work_list', sa.Text(), nullable=True),
    sa.Column('excel_file', sa.String(length=200), nullable=True),
    sa.Column('moved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_service')
    # ### end Alembic commands ###
